// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8OnmHPdf3MYmV5SzGJR7oYDTsPAkO-Hc',
    appId: '1:132626368046:web:ca3faf08b33307b86f41bf',
    messagingSenderId: '132626368046',
    projectId: 'campusconnect-3f38d',
    authDomain: 'campusconnect-3f38d.firebaseapp.com',
    storageBucket: 'campusconnect-3f38d.firebasestorage.app',
    measurementId: 'G-425T7FEWQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBftaIJkMor8rYDZ4-fZRLzEW-gkhcEUQ4',
    appId: '1:132626368046:android:cff399d4cb23469e6f41bf',
    messagingSenderId: '132626368046',
    projectId: 'campusconnect-3f38d',
    storageBucket: 'campusconnect-3f38d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsEctHARAye4y3guQKcntxVNvkAxN4wPE',
    appId: '1:132626368046:ios:14a63da25f4910c96f41bf',
    messagingSenderId: '132626368046',
    projectId: 'campusconnect-3f38d',
    storageBucket: 'campusconnect-3f38d.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsEctHARAye4y3guQKcntxVNvkAxN4wPE',
    appId: '1:132626368046:ios:14a63da25f4910c96f41bf',
    messagingSenderId: '132626368046',
    projectId: 'campusconnect-3f38d',
    storageBucket: 'campusconnect-3f38d.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8OnmHPdf3MYmV5SzGJR7oYDTsPAkO-Hc',
    appId: '1:132626368046:web:193ee2fd5d45a4616f41bf',
    messagingSenderId: '132626368046',
    projectId: 'campusconnect-3f38d',
    authDomain: 'campusconnect-3f38d.firebaseapp.com',
    storageBucket: 'campusconnect-3f38d.firebasestorage.app',
    measurementId: 'G-8MDYP34MFQ',
  );
}
